#! /bin/sh

icon="$HOME/.config/i3lock/lock.png"
img="$HOME/.cache/i3lock.png"
rm $img

scrot $img
# Pixelate image
magick $img -scale 5% -scale 2000% $img
magick $img $icon -gravity center -composite $img
i3lock -e -i $img
