#!/bin/bash

# https://github.com/cdown/mpdmenu

all_name='[ALL]'
mode=library

if [ -n "$WAYLAND_DISPLAY" ] && command -v fuzzel >/dev/null 2>&1; then
	menucmd="fuzzel -d -l 40"
elif [ -n "$DISPLAY" ] && command -v dmenu >/dev/null 2>&1; then
	menucmd="dmenu -c -l 40"
fi

d_artist() {
	mpc list artist | sort -f | $menucmd -p "Artist: ${dmenu_args[@]}"
}

d_album() {
	local artist="$1"
	local albums

	mapfile -t albums < <(mpc list album artist "$artist")
	if (( ${#albums[@]} > 1 )) ; then
		{
			printf '%s\n' "$all_name"
			printf '%s\n' "${albums[@]}" | sort -f
		} | $menucmd -p "Album: ${dmenu_args[@]}"
	else
		# We only have one album, so just use that.
		printf '%s\n' "${albums[0]}"
	fi
}

d_tracks() {
	local format="%position% %artist% -"
	local extra_format="%title%"
	local track
	local num_extras

	# If all tracks are from the same artist and album, no need to display that
	num_extras=$(mpc playlist -f "$extra_format" | uniq | wc -l)
	(( num_extras == 1 )) || format+=" $extra_format"

	track=$(mpc playlist -f "$format" | $menucmd -p "Track: ${dmenu_args[@]}")
	printf '%s' "${track%% *}"
}

d_playlists() {
	mpc lsplaylists | sort | $menucmd -p "Playlist: ${dmenu_args[@]}"
}

i=2

for arg do
	if [[ $arg == :: ]]; then
		dmenu_args=( "${@:$i}" )
		break
	fi

	case "$arg" in
		-t) mode=tracks ;;
		-l) mode=library ;;
		-p) mode=playlists ;;
	esac

	let i++
done

case "$mode" in
	tracks)
		mpc play "$(d_tracks)" >/dev/null
	;;
	library)
		artist=$(d_artist)
		[[ $artist ]] || exit 1

		album=$(d_album "$artist")
		[[ $album ]] || exit 2

		mpc clear
		if [[ $album == "$all_name" ]]; then
			mpc find artist "$artist" | sort | mpc add
		else
			mpc find artist "$artist" album "$album" | sort | mpc add
		fi
		mpc play >/dev/null
	;;
	playlists)
		chosen_playlist=$(d_playlists)
		[[ $chosen_playlist ]] || exit 1
		mpc clear
		mpc load "$chosen_playlist"
		mpc play >/dev/null
	;;
esac
