# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#121212'
foreground='#D9BC82'
cursor='#B83B2E'

# Colors
color0='#121212'
color1='#B83B2E'
color2='#B3AA54'
color3='#D99B36'
color4='#7D98B3'
color5='#A66153'
color6='#D97B4C'
color7='#D9C3AD'
color8='#515151'
color9='#B83B2E'
color10='#B3AA54'
color11='#D99B36'
color12='#7D98B3'
color13='#A66153'
color14='#D97B4C'
color15='#D9C3AD'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
